valeurA = input("valeur de A ")
valeurB = input("valeur de B ")
valeurEntiereA = int(valeurA)
valeurEntiereB = int(valeurB)
resultat = (valeurEntiereA + valeurEntiereB)
print("le resultat est ",resultat)